name: move_env
channels:
- conda-forge
- defaults
- anaconda
dependencies:
- python>=3.8
- jupyter
- jupyterlab>=3.0
- pip
- matplotlib
- numpy
- tqdm
- missingno
- pyjanitor
- black
- nbstripout
- pylint
- ipykernel
- ipywidgets
- hvplot
- bokeh
- holoviews
- mkl
- mkl-service
- pre-commit
- mamba
- pyprojroot
- faker
- python-graphviz
- watermark
- pip:
  - mkdocs
  - mkdocs-material
  - mknotebooks
  - daft
